# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-b6565d15-c832-4aeb-9bf4-73aa91821a0a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b6565d15-c832-4aeb-9bf4-73aa91821a0a".device = "/dev/disk/by-uuid/b6565d15-c832-4aeb-9bf4-73aa91821a0a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/28D4-CE18";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/0e2f0d5a-e483-42aa-8746-4c3316190be1"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
